paginate: 5
paginate_path: "/blog/pages/:num/"
excerpt_separator: "<!-- more -->"
permalink: /blog/posts/:year/:month/:day/:title
defaults:
  -
    scope:
      path: "release-1"
    values:
      layout: "releases-version-1"
plugins:
  - jekyll-paginate